avatar: /img/avatar.gif

footer:
  since: 2018
  icon: meh-o

beian:
  icp: 鄂ICP备17007175号-1

upyun:
    enable: true
    icon: https://photo.hushhw.cn/images/又拍云120180930001119303.png
    url: https://www.upyun.com/index.html

recommended_posts:
  enable: true

# 播放器
aplayer:
 enable: true

social:
  E-Mail: 
    enable: true
    url: mailto:hushhw123@gmail.com
    icon: envelope
  GitHub: 
    enable: true
    url: https://github.com/hushhw
    icon: github
  微博: 
    enable: true
    url: https://weibo.com/1929679982
    icon: weibo
  Instagram: 
    enable: true
    url: https://instagram.com/hushhw
    icon: instagram
  Telegram:
    enable: true
    url: https://t.me/hushhw
    icon: telegram
  #知乎: 
    #enable: true
    #url: http://www.zhihu.com/people/hu-song-19
    #icon: quora
  
  #CSDN: 
    #enable: true
    #url: http://blog.csdn.net/hushhw
    #icon: code
  #网易云音乐: 
    #enable: true
    #url: https://music.163.com/#/user/home?id=96709780
    #icon: music

disqus:  ## Your disqus_shortname, e.g. username
uyan: ## Your uyan_id. e.g. 1234567
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
gitalk:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner:  ## Your GitHub ID, e.g. username
  repo:  ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id:  ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret:  ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin:  ## Github repo owner and collaborators, only these guys can initialize github issues.
valine: ## https://valine.js.org
  enable: true ## If you want to use Valine comment system, please set the value to true.
  appid: YVxvrCNxpTLOcs83UfKCUOaI-gzGzoHsz ## Your LeanCloud application App ID, e.g. pRBBL2JR4N7kLEGojrF0MsSs-gzGzoHsz
  appkey: 5eaXH2FJm2nxSBIQL4INFBbW ## Your LeanCloud application App Key, e.g. tjczHpDfhjYDSYddzymYK1JJ
  notify: false ## Mail notifier, see https://github.com/xCss/Valine/wiki/Valine-评论系统中的邮件提醒设置
  verify: false ## Validation code.
  placeholder: 居然什么也不说，哼 ## Comment box placeholders.
  avatar: 'robohash' ## Gravatar type, see https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  pageSize: 10 ## Number of comments per page.
  guest_info: nick,mail,link ## Attributes of reviewers.

google_site_verification: 
baidu_site_verification: 
google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-132675789-2 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 972cc0516975a00c2c5900eb5e98039d ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
fancybox: true ## If you want to use fancybox please set the value to true.
show_archive_count: true
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: true ## If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
busuanzi: ## If you want to use Busuanzi page views please set the value to true.
  enable: true ## 开启或关闭不蒜子
  page_pv: true ## 单篇文章访问量
  site_pv: true ## 网站总访问量
  site_uv: true ## 网站总访客数
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
toc_on_small_screens: false
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: '100,99,98' ## RGB value of the color, e.g. "100,99,98"
  opacity: 0.7 ## Transparency of lines, e.g. "0.7"
  zIndex: -1 ## The z-index property of the background, e.g. "-1"
  count: 150  ## Quantity of lines, e.g. "150"
donate:
  enable: false ## If you want to display the donate button after each post, please set the value to true and fill the following items on your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github:  ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: hushhw ## Your author name, e.g. tufu9441
  copyright_text:  ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

menu:
  - page: tech
    directory: tech/
    icon: fa-battery-full
  #- page: eassy
  #  directory: life/
  #  icon: fa-file-text
  #- page: photo
  #  directory: photos/
  #  icon: fa-photo
  #- page: book
  #  directory: books/
  #  icon: fa-book
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: tags
    directory: tags/
    icon: fa-tag
  #- page: music
  #  directory: music/
  #  icon: fa-music
  #- page: movie
  #  directory: movies/
  #  icon: fa-film
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: about, search, category, tag, recent_posts, rencent_comments and links.
  - about
  - search
  - tag
  - category
  - recent_posts
  - archivelist
  - links

links:
  - title: HEYBY
    url: http://www.heyby.cn/
  - title: Not determined yet
    url: https://counter2015.com/

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

featuredsize: 1

# Static files
js: js
css: css

# Theme version
version: 0.0.0

